[server]
enableStaticServing = true

[[theme.fontFaces]]
family="inter-regular"
url="app/static/InterVariable.ttf"
style="normal"
# weight="400"

[[theme.fontFaces]]
family="inter-semibold"
url="app/static/InterVariable.ttf"
style="normal"
# weight="600"

[theme]
font = "inter-regular, sans-serif"
headingFont = "inter-regular, sans-serif"

primaryColor ="#1471b0"
base = "light"
